//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int Product_id { get; set; }
        public string Email { get; set; }
        public string Product_type { get; set; }
        public string Product_name { get; set; }
        public decimal Product_price { get; set; }
        public double Product_weight { get; set; }
        public string Product_description { get; set; }
    }
}
